# Generated by Django 3.0.7 on 2020-06-07 19:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200607_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='time_posted',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='date_posted',
            field=models.DateField(),
        ),
    ]
